"""empty message

Revision ID: 978fb3100c21
Revises: d3a2ad8b287a
Create Date: 2019-08-27 14:20:35.138000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978fb3100c21'
down_revision = 'd3a2ad8b287a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_order_info', sa.Column('order_id', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ih_order_info', 'order_id')
    # ### end Alembic commands ###
